name: Provision GitHub Tokens
description: Declare GitHub tokens in your repos, and rotate them automatically
author: Ghalactic
branding:
  icon: key
  color: blue
runs:
  using: node20
  main: dist/main.js
