name: Provision GitHub Tokens
description: Declare GitHub tokens in your repos, and rotate them automatically
author: Ghalactic
inputs:
  provisionApps:
    description: >-
      Apps to use for provisioning tokens, encoded as a YAML (or JSON) array.
      The schema at
      https://ghalactic.github.io/provision-github-tokens/schema/provision-apps.v1.schema.json
      can be used to validate the input.
    required: true
branding:
  icon: key
  color: blue
runs:
  using: node20
  main: dist/main.js
