name: Provision GitHub Tokens
description: Declare GitHub tokens in your repos, and rotate them automatically
author: Ghalactic
inputs:
  apps:
    description: >-
      Apps to use for provisioning tokens, encoded as a YAML (or JSON) array.
      The schema at
      https://ghalactic.github.io/provision-github-tokens/schema/apps.v1.schema.json
      can be used to validate the input.
    required: true
  token:
    description: >-
      The GitHub token to use when reading the provider config file.
    default: ${{ github.token }}
  configPath:
    description: >-
      Path to the provider config file, relative to the root of the repository.
    required: false
    default: .github/ghalactic/provision-github-tokens.provider.yml
branding:
  icon: key
  color: blue
runs:
  using: node20
  main: dist/main.js
