# yaml-language-server: $schema=https://ghalactic.github.io/provision-github-tokens/schema/provider.v1.schema.json

permissions:
  rules:
    - description: Any consumer can read metadata from anywhere
      resources:
        - accounts: ["*"]
          noRepos: true
          allRepos: true
          selectedRepos: ["*"]
      consumers: ["*", "*/*"]
      permissions:
        metadata: read

provision:
  rules:
    secrets:
      - description: Any requester can provision any secrets to itself
        secrets: ["*"]
        requesters: ["*/*"]
        to:
          github:
            repo:
              actions: allow
              codespaces: allow
              dependabot: allow
              environments:
                "*": allow
