name: Run action for CI
run-name: Run action for CI (${{ inputs.label }})

on:
  workflow_dispatch:
    inputs:
      label:
        description: Human-readable label for this run
        type: string

jobs:
  run:
    name: Run action for CI
    uses: ./.github/workflows/internal-run-action.yml
    secrets: inherit
